### ISSUE TITLE
TypeError: DMX is not a constructor.

### ISSUE THREAD

**Issue by 44yk44** [node-dmx/dmx-ts#10]
Hello everyone, 

Just started coding recently, and I'm also a fresh GitHub user so I'm sorry if this is not applicable here.

I'm trying to use this library with Electron and for some reason, I get an error:
TypeError: DMX is not a constructor.

I've used the older node-dmx (not typescript) previously with Electron and it worked fine, so I am not sure what am I doing wrong here.

Any help will be appreciated.

Thanks!

**Comment by Granjow** [comment]
Hi @44yk44 , could you show some example code where the problem occurs?

**Comment by hrueger** [comment]
And it would be interesting to know whether you're trying to use it in the main or the renderer thread and what electron version you're using.

**Comment by 44yk44** [comment]
Hi @Granjow  and @hrueger ,

I used electron-vue-template version 0.1.0 [LINK ](https://github.com/Deluze/electron-vue-template) when starting my project which uses electron 16.0.7.

When I got the error I tried to first get rid of any code that I wrote myself,  so I installed the latest electron forge (regular and typescript versions) and also the more recent electron-vue-template version but I got the same error in all of them so I'm pretty sure I am doing something wrong.  - they use electron 20.1.0.

The only code I inserted was:
```
const DMX = require('dmx-ts');

const dmx = new DMX();

const run = async () => {
  const universe = await dmx.addUniverse('demo', new NullDriver());

  let on = false;

  setInterval(() => {
    if (on) {
      on = false;
      universe.updateAll(0);
      console.log('off');
    } else {
      on = true;
      universe.updateAll(250);
      console.log('on');
    }
  }, 1000);
};

run();
```
  

in the main thread to the buttom of main.js/main.ts file.

By the way:
Running on Ubuntu 20.04.5 LTS
Node v16.17.0
npm v8.15.0

**Comment by hrueger** [comment]
Please try
```TS
const { DMX } = require("dmx-ts");
```

**Comment by 44yk44** [comment]
> Please try
> 
> ```ts
> const { DMX } = require("dmx-ts");
> ```

 Got it working by adding:
 ```
const { DMX } = require("dmx-ts");
const { NullDriver } = require("dmx-ts");

 ```
Thank you very much for the help and for your awesome work!

**Comment by hrueger** [comment]
You're welcome.
It seems like the readme is not correct there, I'll fix that soon.
Can this issue be closed?

**Comment by hrueger** [comment]
If you want, you can optimize your code by using
```TS
const { DMX, NullDriver } = require("dmx-ts");
```
instead of the two require calls 😃

**Comment by 44yk44** [comment]
Thanks for the tip (:
You can close the issue however I have some questions regarding driver options and SACN min refresh rate.
Should I open a new issue for that or post them here?

**Comment by hrueger** [comment]
> Should I open a new issue for that or post them here?

That's a good idea, then we can keep things separate 👍
