### ISSUE TITLE
Artnet Problems

### ISSUE THREAD

**Issue by hrueger** [node-dmx/dmx-ts#6]
I have problems sending artnet data: my interface does not receive the universe. When looking at the code, it seems like strange things are going on there:

https://github.com/node-dmx/dmx-ts/blob/9942e121fc9c3646245b0c290c7d088097fb022d/src/drivers/artnet.ts#L44

Why are we stopping the universe here?

**Comment by Granjow** [comment]
Thanks for fixing! :)
